#!/bin/bash

# Script to help download LinkedIn profile pictures
# Note: This script provides instructions and placeholders

echo "=== LinkedIn Profile Image Setup ==="
echo ""
echo "To add LinkedIn profile pictures for your speakers:"
echo ""
echo "1. MANUAL METHOD (Recommended):"
echo "   - Visit each LinkedIn profile in your browser"
echo "   - Right-click on the profile picture"
echo "   - Select 'Save image as...' or 'Copy image'"
echo "   - Save as:"
echo "     * christoph-koenig.jpg (for Christoph König)"
echo "     * marc-rufer.jpg (for Marc Rufer)"
echo "   - Place files in: assets/images/"
echo ""
echo "2. LINKEDIN URLS:"
echo "   - Christoph König: https://www.linkedin.com/in/christoph-k%C3%B6nig/"
echo "   - Marc Rufer: https://www.linkedin.com/in/marcrufer/"
echo ""
echo "3. IMAGE REQUIREMENTS:"
echo "   - Format: JPG or PNG"
echo "   - Size: 200x200px (square) recommended"
echo "   - Professional headshot"
echo ""
echo "4. FALLBACK:"
echo "   - If images fail to load, default-speaker.svg will be shown"
echo "   - This ensures the website always displays properly"
echo ""
echo "=== IMPORTANT LEGAL NOTE ==="
echo "Always ensure you have permission to use profile pictures."
echo "For public events, it's best practice to:"
echo "- Ask speakers for permission"
echo "- Request they provide their own professional headshots"
echo "- Use photos that speakers have explicitly approved for event promotion"
echo ""